FROM golang:1.22.2-alpine as builder

RUN go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

FROM alpine:latest

COPY --from=builder /go/bin/migrate /usr/local/bin/migrate

COPY ./postgres/migrations /migrations

CMD migrate -path=/migrations/ -database "postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:5432/${DB_NAME}?sslmode=disable" up
