FROM golang:1.22.1-alpine as dependencies

WORKDIR /app

ARG FIREBASE_SERVICE_ACCOUNT_KEY_BASE64

RUN apk add --no-cache make 

COPY go.mod ./
COPY go.sum* ./

RUN go mod download 

COPY . .

RUN echo $FIREBASE_SERVICE_ACCOUNT_KEY_BASE64 | base64 -d > firebase/firebase_service_account_key.json

RUN make build

FROM alpine:latest

WORKDIR /app

COPY --from=dependencies /app/tmp/main /app/main
COPY --from=dependencies /app/firebase/firebase_service_account_key.json /app/firebase/firebase_service_account_key.json

CMD ["/app/main"]

