apiVersion: apps/v1
kind: Deployment
metadata:
  name: spaces
  labels:
    app: spaces
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      app: spaces
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  template:
    metadata:
      labels:
        app: spaces
    spec:
      containers:
      - name: spaces-server
        image: DOCKERHUB_IMAGE
        env: 
        - name: ENVIRONMENT
          value: staging
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
      imagePullSecrets:
      - name: docker-hub-secret

