apiVersion: v1
kind: Service
metadata:
  name: spaces-prod
spec:
  type: LoadBalancer
  selector:
    project: spaces
    env: prod
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 8080