{{- if .Values.dbPasswordSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql
  labels:
    {{- include "server.labels" . | nindent 4 }} 
data:
  password: {{ .Values.postgresql.auth.password | b64enc | quote }}
{{- end }}