apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.dockerHubSecret.name }}
  labels:
    {{- include "server.labels" . | nindent 4 }} 
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.secrets.dockerHubSecret.valueBase64 | quote }}
