apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "server.name" . }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ include "server.host" . }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "server.name" . }}
            port:
              number: 80
  - host: www.{{ include "server.host" . }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "server.name" . }}
            port:
              number: 80