apiVersion: v1
kind: Service
metadata:
  name: {{ include "server.name" . }}
  labels: 
    {{- include "server.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  selector:
    {{- include "server.selectorLabels" . | nindent 4 }} 
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: {{ .Values.service.internalPort }}