name: CI

# TODO: only run when server or .github directory contents change
on: 
  push:
    branches:
      - main
    paths: 
      - 'server/**'
      - '.github/**'
  pull_request:
    branches:
      - main
    paths: 
      - 'server/**'
      - '.github/**'

jobs:
  build-and-push:
    env: # same for prod and staging
      IMAGE: "${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPO }}:${{ github.ref_name }}-${{ github.sha }}"
    defaults:
      run:
        working-directory: server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # same
        with:
          sparse-checkout: |
            .github
            server
        
      - uses: azure/k8s-set-context@v4 # same (maybe with different namespace)
        with:
          kubeconfig: ${{ secrets.LINODE_KUBECONFIG }} # must be the kubeconfig itself, not the path to it

      - name: Build the Docker Image # same (different FIREBASE_SERVICE_ACCOUNT_KEY_BASE64 secret)
        run: docker build -f Dockerfile.prod -t ${{ env.IMAGE }} --build-arg FIREBASE_SERVICE_ACCOUNT_KEY_BASE64="${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY_BASE64}}" .

      - name: Login to Docker Hub #same
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Push the Docker Image # same
        run: docker push ${{ env.IMAGE }}

      # - name: Create namespace  # same (different namespace)
      #   run: kubectl apply -f k8s/spaces_ns.yml

      # - name: Set new current namespace # same (different namespace)
      #   run: kubectl config set-context --current --namespace=spaces

      - name: Create Dockerhub secret # maybe same (secret must be accessible in all namespaces)
        run: |
          sed -i'' \
          -e "s/DOCKERHUB_SECRET/$(cat ~/.docker/config.json | base64 -w 0)/g" \
          k8s/spaces-dockerhub_secret.yml
          kubectl apply -f k8s/spaces-dockerhub_secret.yml --namespace=spaces

      - name: Apply Deployment # different namespace, deployment file
        run: |
          sed -i'' \
          -e "s|DOCKERHUB_IMAGE|${{ env.IMAGE }}|g" \
          k8s/spaces-prod_deploy.yml
          kubectl apply -f k8s/spaces-prod_deploy.yml --namespace=spaces

      - name: Apply Service # different namespace, service file
        run: kubectl apply -f k8s/spaces-prod_svc.yml --namespace=spaces

      - name: Delete old Images on Docker Hub # different env vars (REGEX, DAYS_AGO, NTH_NEWEST)
        run: /bin/bash bash_scripts/delete_old_images/delete_old_images.sh
        env:
          REGEX: "${{ github.ref_name }}-"
          DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
          DOCKERHUB_REPO: ${{ vars.DOCKERHUB_REPO }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}