name: Manual rollback

on:
  workflow_dispatch: 
    inputs:
      revision:
        description: 'Revision to rollback to'
        required: true
        default: 0
        type: number
      environment:
        description: 'Environment to perform rollback on'
        required: true
        type: choice
        options:
          - 'prod'
          - 'staging'
        default: 'prod'

jobs:
  rollback:
    name: Rollback
    defaults:
      run:
        working-directory: services/server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
        with:
          sparse-checkout: |
            .github
            services

      - name: Check Required variables and secrets
        run: |
          if [[ -z "${{ secrets.LINODE_KUBECONFIG }}" ]]; then
            echo "LINODE_KUBECONFIG secret is missing";
            exit 1;
          fi

          if [[ -z "${{ vars.HELM_VERSION }}" ]]; then
            echo "HELM_VERSION variable is missing";
            exit 1;
          fi

      - name: Set up Kubernetes context
        run: |
          echo "${{ secrets.LINODE_KUBECONFIG }}" > ./kubeconfig
          echo "KUBECONFIG=$PWD/kubeconfig" >> $GITHUB_ENV

      - uses: azure/setup-helm@v4.1.0
        with:
          version: "${{ vars.HELM_VERSION }}"

      - name: Apply Helm Chart
        run: |
          helm rollback server-${{ inputs.environment }} ${{ inputs.revision }}